#!/usr/bin/env bash
# This script displays username, user id, and home directory from /etc/passwd
while IFS=: read -r username pass uid gid info home shell; do
    echo "$username:$uid:$home"
done < /etc/passwd
